export function Footer() {
  return (
    <footer className="border-t-2 border-[var(--border-color)] mt-12 py-8 px-4">
      <div className="max-w-7xl mx-auto text-center">
        <h2 className="headline-lg text-2xl mb-2">The Nansen Times</h2>
        <p className="text-xs text-[var(--text-secondary)] mb-4 font-[family-name:var(--font-sans)]">
          WHEN WHALES MOVE, WE PRINT
        </p>

        <div className="ornament-divider max-w-md mx-auto mb-4">
          <span className="text-xs tracking-[0.2em] text-[var(--text-secondary)] font-[family-name:var(--font-sans)]">
            ◆
          </span>
        </div>

        <p className="text-xs text-[var(--text-secondary)] font-[family-name:var(--font-sans)]">
          Powered by{' '}
          <a
            href="https://nansen.ai"
            target="_blank"
            className="underline hover:no-underline"
          >
            Nansen
          </a>.
        </p>
        <p className="text-xs text-[var(--text-secondary)] mt-2 font-[family-name:var(--font-sans)]">
          Articles generated by AI. Not financial advice. DYOR.
        </p>
      </div>
    </footer>
  );
}
